name: "zx"
services:
  doc_site:
    build:
      context: ../
      dockerfile: site/Dockerfile
    container_name: "ziex.dev"
    restart: unless-stopped
    networks:
      - npm

networks:
  npm:
    driver: bridge
